name: Build and push Docker images

on:
  workflow_dispatch:
  schedule:
    # every monday at 2am
    - cron: "0 1 * * 1"

jobs:
  base:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: base
      context: base
      test: true
      base_image: ubuntu:22.04
      base_image_gpu: nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04
      external_base_image: true
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  nodejs-minimal:
    needs: [base]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: nodejs-minimal
      context: nodejs-minimal
      test: true
      base_image: base
      nodejs_version_1: 19.7.0
      nodejs_version_2: 18.14.2
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  vscode-nodejs:
    needs: [nodejs-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-nodejs
      context: vscode
      test: true
      base_image: nodejs-minimal
      nodejs_version_1: 19.7.0
      nodejs_version_2: 18.14.2
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  python-minimal:
    needs: [base]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-minimal
      context: python-minimal
      test: true
      base_image: base
      python_version_1: 3.10.9
      python_version_2: 3.9.16
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  pyspark-jigsaw:
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: pyspark-jigsaw
      context: spark-jigsaw
      test: true
      base_image: python-minimal
      python_version_1: 3.10.9
      python_version_2: 3.9.16
      spark_version: 3.3.1
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  vscode-pyspark-jigsaw:
    needs: [pyspark-jigsaw]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-pyspark-jigsaw
      context: vscode
      test: true
      base_image: pyspark-jigsaw
      python_version_1: 3.10.9
      python_version_2: 3.9.16
      spark_version: 3.3.1
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
